// Third-party license policy for redistribution (CN offline package embedding)
// and provenance document generation.
//
// Three license classes:
//   permissive  license text unambiguously allows verbatim redistribution in a
//               free modpack (attribution is satisfied by THIRD_PARTY_MODS.md)
//   forbidden   All-Rights-Reserved / unknown — never embedded without an
//               explicit lockfile override documenting author permission
//   review      custom LicenseRef-* / NC licenses — not embedded unless the
//               lockfile carries redistribution:"allow" + redistribution_note
//
// A locked entry may set:
//   redistribution: "allow"  maintainer asserts redistribution is permitted
//                            (requires redistribution_note citing the basis)
//   redistribution: "deny"   never embed, even if the SPDX id looks permissive
//   redistribution_note      free-text justification recorded in reports
// Entries without the field fall back to the license class.

// SPDX ids that clearly permit verbatim redistribution of the binary jar.
const PERMISSIVE = new Set([
  'MIT', 'MIT-0', '0BSD', 'BSD-2-Clause', 'BSD-3-Clause', 'ISC',
  'Apache-2.0', 'Unlicense', 'CC0-1.0', 'WTFPL', 'Zlib',
  'LGPL-2.1-only', 'LGPL-2.1-or-later', 'LGPL-3.0-only', 'LGPL-3.0-or-later',
  'GPL-2.0-only', 'GPL-2.0-or-later', 'GPL-3.0-only', 'GPL-3.0-or-later',
  'AGPL-3.0-only', 'AGPL-3.0-or-later',
  'MPL-1.1', 'MPL-2.0', 'EPL-1.0', 'EPL-2.0', 'EUPL-1.2',
  // LGPL with a dependency carve-out is still LGPL at its core.
  'LicenseRef-LGPL-with-additional-dependency-clause',
]);

const FORBIDDEN_RE = /all[-_ ]rights[-_ ]reserved|\barr\b|unknown/i;

// -> 'permissive' | 'forbidden' | 'missing' | 'review'
export function licenseClass(license) {
  if (!license) return 'missing';
  if (PERMISSIVE.has(license)) return 'permissive';
  if (FORBIDDEN_RE.test(license)) return 'forbidden';
  return 'review';
}

// -> {embed, cls, basis, reason}
//   basis: license | lockfile-allow | lockfile-deny | forbidden | review | missing
export function embedStatus(entry) {
  const cls = licenseClass(entry.license);
  if (entry.redistribution === 'deny') {
    return { embed: false, cls, basis: 'lockfile-deny',
      reason: entry.redistribution_note ?? 'lockfile marks redistribution:"deny"' };
  }
  if (entry.redistribution === 'allow') {
    return { embed: true, cls, basis: 'lockfile-allow',
      reason: entry.redistribution_note ?? 'lockfile marks redistribution:"allow"' };
  }
  switch (cls) {
    case 'permissive':
      return { embed: true, cls, basis: 'license',
        reason: `${entry.license} permits verbatim redistribution` };
    case 'missing':
      return { embed: false, cls, basis: 'missing',
        reason: 'no license recorded — cannot evaluate redistribution rights' };
    case 'forbidden':
      return { embed: false, cls, basis: 'forbidden',
        reason: `${entry.license} does not grant redistribution` };
    default:
      return { embed: false, cls, basis: 'review',
        reason: `${entry.license} needs manual review — stays on official download` };
  }
}

// ---- generated provenance documents ----------------------------------------

const esc = (s) => String(s ?? '—').replaceAll('|', '\\|');

// Full provenance manifest for every locked mod/resource in the client set.
// variants: ordered list of package variant ids built this run ('standard','cn')
// rows: [{entry, type, primary, dispositions: {<variant>: {embed, reason}}}]
//   embed=true  -> file shipped inside the package under overrides/
//   embed=false -> declared in modrinth.index.json, launcher downloads it
export function thirdPartyModsMd({ packName, versionId, minecraft, neoforge, variants, rows }) {
  const vhead = variants.map((v) => ` ${v} |`).join('');
  return `# Third-party mods — provenance manifest / 第三方模组来源清单

- Pack: ${packName} — version \`${versionId}\`
- Minecraft ${minecraft} · NeoForge ${neoforge}
- Generated by tools/package-client.mjs — do not edit by hand.
- Hashes are of the exact files this release ships or references; every
  embedded jar is byte-identical to the file at its official download URL.
- "embedded" = jar travels inside the package under overrides/ (launchers
  cannot hash-verify overrides, so verify against the sums below);
  "remote" = the launcher downloads it from the listed official URL.

| name | version | type | file | license | sha256 | sha512 | project | official download |${vhead}
| --- | --- | --- | --- | --- | --- | --- | --- | --- |${variants.map(() => ' --- |').join('')}
${rows.map(({ entry: m, type, primary, dispositions }) =>
  `| ${esc(m.name)} | ${esc(m.version)} | ${type ?? 'mod'} | \`${esc(m.filename)}\` | ${esc(m.license ?? '—')} | \`${m.sha256}\` | \`${m.sha512}\` | ${esc(m.project_page ?? '—')} | ${esc(primary ?? m.download_url ?? '—')} |` +
  variants.map((v) => {
    const d = dispositions?.[v];
    if (!d) return ' — |';
    return d.embed ? ` embedded — ${esc(d.reason)} |` : ` remote — ${esc(d.reason)} |`;
  }).join('')).join('\n')}
`;
}

// sha256sum -c compatible listing of every embedded file, keyed by the path
// it lands at inside the instance (mods/x.jar, shaderpacks/x.zip, ...).
export function sha256SumsTxt(items /* [{path, sha256}] */) {
  return items.map((i) => `${i.sha256}  ${i.path}`).join('\n') + '\n';
}

// Security notes shipped inside every .mrpack (bilingual, zh primary).
export function securityMd({ packName, versionId, variant, embeddedCount, remoteCount }) {
  const isCn = variant === 'cn';
  return `# Package security notes / 安全说明

${packName} — \`${versionId}\` · variant: **${variant}**

## English

- This is a standard Modrinth \`.mrpack\`. ${isCn
    ? `The CN variant embeds ${embeddedCount} third-party file(s) under \`overrides/\` whose
  licenses permit redistribution; ${remoteCount} remaining file(s) are still
  downloaded from official sources at import.`
    : `${embeddedCount} file(s) are embedded (the pack's own self-built addon plus any
  explicitly justified entries); ${remoteCount} file(s) are downloaded by the
  launcher from official sources — third-party jars are not re-hosted.`}
- Prism Launcher may warn that some mods "were not found on Modrinth/CurseForge".
  That dialog is a generic **safety reminder** for locally-shipped jars, **not a
  virus detection**. Embedded jars are hash-verified at build time and are
  byte-identical to the official files listed in THIRD_PARTY_MODS.md.
- Verify after import: open a shell in the instance's \`.minecraft\` and run
  \`sha256sum -c SHA256SUMS.txt\` (copy it out of this package first), or compare
  \`Get-FileHash -Algorithm SHA256\` output per file.
- Embedded jars are licensed for this pack's distribution only — do not re-host
  or extract them for other projects.

## 中文

- 本包是标准 Modrinth \`.mrpack\`。${isCn
    ? `中国版在 \`overrides/\` 内嵌了 ${embeddedCount} 个许可证明确允许再分发的第三方文件；
  其余 ${remoteCount} 个文件仍由启动器从官方地址下载。`
    : `标准版内嵌 ${embeddedCount} 个文件（自研附属及有明确内嵌理由的条目），
  其余 ${remoteCount} 个文件由启动器从官方地址下载——第三方 jar 不被转售托管。`}
- Prism Launcher 若提示"部分 Mod 未托管于 Modrinth/CurseForge"，那是针对本地
  随包 jar 的**通用安全提醒**，不是病毒检测。内嵌 jar 在打包时已逐字节校验，
  与 THIRD_PARTY_MODS.md 所列官方文件完全一致。
- 校验方法：导入后在实例 \`.minecraft\` 目录执行 \`sha256sum -c SHA256SUMS.txt\`
  （先从包内取出该文件），或用 PowerShell \`Get-FileHash -Algorithm SHA256\`
  逐文件比对。
- 内嵌 jar 仅授权随本包分发，请勿提取后二次上传或用于其他项目。
`;
}
