// Generated by the Ad Astra dimension-preset patcher — see patches/manifest.toml
// Manifest op: create-adastra-presets

#ifndef INCLUDE_ADASTRA_PRESETS
#define INCLUDE_ADASTRA_PRESETS

#if defined ADASTRA_PRESET
    #ifndef EUPHORIA_PATCHES_IS_SPACE_MOD_INSTALLED
        #define EUPHORIA_PATCHES_IS_SPACE_MOD_INSTALLED
    #endif
#endif

#ifdef DIM_ADASTRA_MOON
// Moon: airless vacuum, Earth-like irradiance, and earthshine floor preserve harsh daylight without atmospheric scattering (SCIENCE.md#moon)
#define ADASTRA_LIGHT_MULT 1.15
#define ADASTRA_LIGHT_COLOR vec3(1.0, 0.98, 0.95)
#define ADASTRA_AMBIENT_DAY vec3(0.08, 0.085, 0.09)
#define ADASTRA_AMBIENT_NIGHT vec3(0.04, 0.05, 0.07)
#define ADASTRA_SKY_UP vec3(0.0)
#define ADASTRA_SKY_MID vec3(0.0)
#define ADASTRA_SKY_HORIZON vec3(0.0)
#define ADASTRA_SUNSET_TINT vec3(0.0)
#define ADASTRA_SUN_SIZE_MULT 1.0
#define ADASTRA_SUN_VISIBLE 1
#define ADASTRA_SUN_GLARE_MULT 1.0
#define ADASTRA_MOON_VISIBLE 0
#define ADASTRA_STARS_DAYLIGHT 1
#define ADASTRA_STAR_AMOUNT_OFFSET 2
#define ADASTRA_STAR_BRIGHTNESS_MULT 1.5
#define ADASTRA_FOG_COLOR vec3(0.0)
#define ADASTRA_FOG_DENSITY_MULT 0.0
#define ADASTRA_CLOUDS_ENABLED 0
#define ADASTRA_WEATHER_RAIN_ENABLED 0
#define ADASTRA_WEATHER_SNOW_ENABLED 0
#define ADASTRA_VL_MULT 0.0
#define ADASTRA_AURORA_ENABLED 0
#define ADASTRA_RAINBOW_ENABLED 0
#define ADASTRA_NEBULA_ENABLED 0
#define ADASTRA_SUN_ANGLE_OVERRIDE 0

#elif defined DIM_ADASTRA_MARS
// Mars: a thin dust atmosphere makes an ochre daytime sky, blue reverse-Rayleigh sunsets, moderate haze, and dust shafts (SCIENCE.md#mars)
#define ADASTRA_LIGHT_MULT 0.55
#define ADASTRA_LIGHT_COLOR vec3(1.0, 0.95, 0.85)
#define ADASTRA_AMBIENT_DAY vec3(0.55, 0.42, 0.28)
#define ADASTRA_AMBIENT_NIGHT vec3(0.03)
#define ADASTRA_SKY_UP vec3(0.55, 0.42, 0.28)
#define ADASTRA_SKY_MID vec3(0.65, 0.48, 0.30)
#define ADASTRA_SKY_HORIZON vec3(0.75, 0.56, 0.34)
#define ADASTRA_SUNSET_TINT vec3(0.35, 0.42, 0.55)
#define ADASTRA_SUN_SIZE_MULT 0.63
#define ADASTRA_SUN_VISIBLE 1
#define ADASTRA_SUN_GLARE_MULT 1.0
#define ADASTRA_MOON_VISIBLE 0
#define ADASTRA_STARS_DAYLIGHT 0
#define ADASTRA_STAR_AMOUNT_OFFSET 1
#define ADASTRA_STAR_BRIGHTNESS_MULT 1.0
#define ADASTRA_FOG_COLOR vec3(0.66, 0.47, 0.30)
#define ADASTRA_FOG_DENSITY_MULT 1.0
#define ADASTRA_CLOUDS_ENABLED 0
#define ADASTRA_WEATHER_RAIN_ENABLED 0
#define ADASTRA_WEATHER_SNOW_ENABLED 1
#define ADASTRA_VL_MULT 0.5
#define ADASTRA_AURORA_ENABLED 0
#define ADASTRA_RAINBOW_ENABLED 0
#define ADASTRA_NEBULA_ENABLED 0
#define ADASTRA_SUN_ANGLE_OVERRIDE 25

#elif defined DIM_ADASTRA_VENUS
// Venus: dense orange overcast and surface haze replace direct sunlight; sulfuric virga evaporates before reaching the ground (SCIENCE.md#venus)
#define ADASTRA_LIGHT_MULT 0.0
#define ADASTRA_LIGHT_COLOR vec3(0.18, 0.12, 0.06)
#define ADASTRA_AMBIENT_DAY vec3(0.55, 0.38, 0.18)
#define ADASTRA_AMBIENT_NIGHT vec3(0.03, 0.02, 0.015)
#define ADASTRA_SKY_UP vec3(0.75, 0.48, 0.20)
#define ADASTRA_SKY_MID vec3(0.85, 0.55, 0.22)
#define ADASTRA_SKY_HORIZON vec3(0.90, 0.60, 0.25)
#define ADASTRA_SUNSET_TINT vec3(0.0)
#define ADASTRA_SUN_SIZE_MULT 1.0
#define ADASTRA_SUN_VISIBLE 0
#define ADASTRA_SUN_GLARE_MULT 0.15
#define ADASTRA_MOON_VISIBLE 0
#define ADASTRA_STARS_DAYLIGHT 0
#define ADASTRA_STAR_AMOUNT_OFFSET 0
#define ADASTRA_STAR_BRIGHTNESS_MULT 0.0
#define ADASTRA_FOG_COLOR vec3(0.80, 0.50, 0.20)
// Tempering deviations: 2.5 is the midpoint of the pinned ~2–3 km visibility band scaled to the shader render distance (SCIENCE.md#venus)
#define ADASTRA_FOG_DENSITY_MULT 2.5
#define ADASTRA_CLOUDS_ENABLED 0
#define ADASTRA_WEATHER_RAIN_ENABLED 0
#define ADASTRA_WEATHER_SNOW_ENABLED 0
#define ADASTRA_VL_MULT 0.0
#define ADASTRA_AURORA_ENABLED 0
#define ADASTRA_RAINBOW_ENABLED 0
#define ADASTRA_NEBULA_ENABLED 0
#define ADASTRA_SUN_ANGLE_OVERRIDE 0

#elif defined DIM_ADASTRA_MERCURY
// Mercury: mean irradiance is 9083 W/m2 (6.67x Earth), compressed to a displayable 3.2 while its vacuum keeps sky and fog black (SCIENCE.md#mercury)
#define ADASTRA_LIGHT_MULT 3.2
#define ADASTRA_LIGHT_COLOR vec3(1.0, 0.97, 0.93)
#define ADASTRA_AMBIENT_DAY vec3(0.10, 0.095, 0.09)
#define ADASTRA_AMBIENT_NIGHT vec3(0.03, 0.03, 0.035)
#define ADASTRA_SKY_UP vec3(0.0)
#define ADASTRA_SKY_MID vec3(0.0)
#define ADASTRA_SKY_HORIZON vec3(0.0)
#define ADASTRA_SUNSET_TINT vec3(0.0)
#define ADASTRA_SUN_SIZE_MULT 2.6
#define ADASTRA_SUN_VISIBLE 1
#define ADASTRA_SUN_GLARE_MULT 1.0
#define ADASTRA_MOON_VISIBLE 0
#define ADASTRA_STARS_DAYLIGHT 1
#define ADASTRA_STAR_AMOUNT_OFFSET 2
#define ADASTRA_STAR_BRIGHTNESS_MULT 1.5
#define ADASTRA_FOG_COLOR vec3(0.0)
#define ADASTRA_FOG_DENSITY_MULT 0.0
#define ADASTRA_CLOUDS_ENABLED 0
#define ADASTRA_WEATHER_RAIN_ENABLED 0
#define ADASTRA_WEATHER_SNOW_ENABLED 0
#define ADASTRA_VL_MULT 0.0
#define ADASTRA_AURORA_ENABLED 0
#define ADASTRA_RAINBOW_ENABLED 0
#define ADASTRA_NEBULA_ENABLED 0
#define ADASTRA_SUN_ANGLE_OVERRIDE 0

#elif defined DIM_ADASTRA_GLACIO
// Glacio: a cold, pale atmosphere under a red-orange Proxima-like star keeps snow and aurora while using the chosen fictional axial tilt (SCIENCE.md#glacio)
#define ADASTRA_LIGHT_MULT 0.75
#define ADASTRA_LIGHT_COLOR vec3(1.0, 0.62, 0.38)
#define ADASTRA_AMBIENT_DAY vec3(0.30, 0.36, 0.48)
#define ADASTRA_AMBIENT_NIGHT vec3(0.04, 0.05, 0.07)
#define ADASTRA_SKY_UP vec3(0.30, 0.36, 0.48)
#define ADASTRA_SKY_MID vec3(0.42, 0.44, 0.52)
#define ADASTRA_SKY_HORIZON vec3(0.60, 0.50, 0.46)
#define ADASTRA_SUNSET_TINT vec3(0.55, 0.25, 0.15)
#define ADASTRA_SUN_SIZE_MULT 3.2
#define ADASTRA_SUN_VISIBLE 1
#define ADASTRA_SUN_GLARE_MULT 1.0
#define ADASTRA_MOON_VISIBLE 0
#define ADASTRA_STARS_DAYLIGHT 0
#define ADASTRA_STAR_AMOUNT_OFFSET 1
#define ADASTRA_STAR_BRIGHTNESS_MULT 1.0
#define ADASTRA_FOG_COLOR vec3(0.30, 0.36, 0.48)
#define ADASTRA_FOG_DENSITY_MULT 1.0
#define ADASTRA_CLOUDS_ENABLED 1
#define ADASTRA_WEATHER_RAIN_ENABLED 0
#define ADASTRA_WEATHER_SNOW_ENABLED 1
#define ADASTRA_VL_MULT 1.0
#define ADASTRA_AURORA_ENABLED 1
#define ADASTRA_RAINBOW_ENABLED 0
#define ADASTRA_NEBULA_ENABLED 1
#define ADASTRA_SUN_ANGLE_OVERRIDE 20

#elif defined DIM_ADASTRA_ORBIT
// Orbit: shared Earth-orbit baseline in vacuum preserves harsh sunlight and daylight stars with no scattering, weather, or optical shafts (SCIENCE.md#orbit)
#define ADASTRA_LIGHT_MULT 1.2
#define ADASTRA_LIGHT_COLOR vec3(1.0, 0.99, 0.97)
#define ADASTRA_AMBIENT_DAY vec3(0.04, 0.04, 0.045)
#define ADASTRA_AMBIENT_NIGHT vec3(0.03, 0.03, 0.035)
#define ADASTRA_SKY_UP vec3(0.0)
#define ADASTRA_SKY_MID vec3(0.0)
#define ADASTRA_SKY_HORIZON vec3(0.0)
#define ADASTRA_SUNSET_TINT vec3(0.0)
#define ADASTRA_SUN_SIZE_MULT 1.0
#define ADASTRA_SUN_VISIBLE 1
#define ADASTRA_SUN_GLARE_MULT 1.0
#define ADASTRA_MOON_VISIBLE 0
#define ADASTRA_STARS_DAYLIGHT 1
#define ADASTRA_STAR_AMOUNT_OFFSET 2
#define ADASTRA_STAR_BRIGHTNESS_MULT 1.5
#define ADASTRA_FOG_COLOR vec3(0.0)
#define ADASTRA_FOG_DENSITY_MULT 0.0
#define ADASTRA_CLOUDS_ENABLED 0
#define ADASTRA_WEATHER_RAIN_ENABLED 0
#define ADASTRA_WEATHER_SNOW_ENABLED 0
#define ADASTRA_VL_MULT 0.0
#define ADASTRA_AURORA_ENABLED 0
#define ADASTRA_RAINBOW_ENABLED 0
#define ADASTRA_NEBULA_ENABLED 0
#define ADASTRA_SUN_ANGLE_OVERRIDE 0

#endif

#endif //INCLUDE_ADASTRA_PRESETS
