// GENERATED by tools/build-pack.mjs — edit design/content.json, not this file.
StartupEvents.registry('item', (e) => {
  e.create('modpack:engineering_assembly').texture('modpack:item/engineering_assembly')
  e.create('modpack:information_interface').texture('modpack:item/information_interface')
  e.create('modpack:heavy_industry_control').texture('modpack:item/heavy_industry_control')
  e.create('modpack:reactor_control').texture('modpack:item/reactor_control')
  e.create('modpack:space_control_core').texture('modpack:item/space_control_core')
  e.create('modpack:colony_maintenance').texture('modpack:item/colony_maintenance')
  e.create('modpack:quantum_control').texture('modpack:item/quantum_control')
  e.create('modpack:anomaly_analysis').texture('modpack:item/anomaly_analysis')
  e.create('modpack:industrial_console').texture('modpack:item/industrial_console')
  e.create('modpack:armory_workbench').texture('modpack:item/armory_workbench')
  e.create('modpack:logistics_console').texture('modpack:item/logistics_console')
  e.create('modpack:life_support_console').texture('modpack:item/life_support_console')
});
