// GENERATED by tools/build-pack.mjs — edit design/content.json, not this file.
StartupEvents.registry('item', (e) => {
  e.create('modpack:engineering_assembly').texture('immersiveengineering:item/material_component_iron')
  e.create('modpack:information_interface').texture('ae2:item/logic_processor')
  e.create('modpack:heavy_industry_control').texture('immersiveengineering:item/material_component_steel')
  e.create('modpack:reactor_control').texture('ic2cre:item/reactor/containment_plating')
  e.create('modpack:space_control_core').texture('ad_astra:item/etrionic_core')
  e.create('modpack:colony_maintenance').texture('immersiveengineering:item/material_component_electronic')
  e.create('modpack:quantum_control').texture('ae2:item/quantum_entangled_singularity')
  e.create('modpack:anomaly_analysis').texture('ae2:item/singularity')
  e.create('modpack:industrial_console').texture('immersiveengineering:item/blueprint')
  e.create('modpack:armory_workbench').texture('ae2:item/advanced_card')
  e.create('modpack:logistics_console').texture('ae2:item/basic_card')
  e.create('modpack:life_support_console').texture('ae2:item/card_energy')
  e.create('modpack:service_medal').texture('ic2cre:item/coin')
});
