[advancements]
locked = ["id:starforge:first_launch", "id:starforge:moon_landing", "id:starforge:mars_landing", "id:starforge:belt_arrival", "id:starforge:alien_artifact", "id:starforge:alien_ruins", "id:starforge:colony_established"]
