package com.starforge.compat;

import java.util.List;
import java.util.Optional;
import net.minecraft.ChatFormatting;
import net.minecraft.advancements.AdvancementHolder;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.Holder;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.PlayerAdvancements;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.component.CustomData;
import net.minecraft.world.item.component.ResolvableProfile;
import net.neoforged.neoforge.common.util.FakePlayer;
import net.neoforged.neoforge.event.entity.living.LivingDeathEvent;
import net.neoforged.neoforge.event.entity.living.LivingEntityUseItemEvent;
import net.neoforged.neoforge.event.entity.player.ItemTooltipEvent;

/**
 * Hidden easter egg: the first time a player kills another real player, the
 * killer receives the victim's head as a special edible item and earns the
 * hidden advancement {@code starforge:edible_player_head} (generated by
 * build-pack.mjs with a {@code minecraft:impossible} criterion, so it can only
 * be granted from here).
 * <p>
 * The reward is a plain {@code minecraft:player_head} carrying a marker in its
 * {@code minecraft:custom_data} component; vanilla heads are unaffected. Eating
 * it applies infinite Regeneration VI and Wither VI as ordinary mob effects
 * (milk, death and {@code /effect clear} all work).
 */
public final class EdiblePlayerHead {
    private EdiblePlayerHead() {}

    // Must match the generated advancement at kubejs/data/starforge/advancement/.
    private static final ResourceLocation ADVANCEMENT_ID =
        ResourceLocation.fromNamespaceAndPath("starforge", "edible_player_head");
    private static final String CRITERION = "triggered";

    // custom_data marker keys on the special head.
    private static final String TAG_MARKER = "starforge:edible_player_head";
    private static final String TAG_VICTIM_UUID = "starforge:victim_uuid";
    private static final String TAG_VICTIM_NAME = "starforge:victim_name";

    private static final String NAME_KEY = "item.starforge_compat.edible_player_head";
    private static final String EFFECTS_KEY = "tooltip.starforge_compat.edible_player_head.effects";
    private static final String SCRAMBLE_KEY = "tooltip.starforge_compat.edible_player_head.line";
    private static final ChatFormatting[] SCRAMBLE_COLORS = {
        ChatFormatting.DARK_PURPLE, ChatFormatting.AQUA, ChatFormatting.YELLOW,
        ChatFormatting.RED, ChatFormatting.GREEN
    };

    /**
     * First player-kill grant: verify the credit is a real player (not suicide,
     * mob, environment or FakePlayer), skip when the advancement is already
     * done, then hand over the head and award the advancement.
     */
    public static void onPlayerDeath(LivingDeathEvent event) {
        if (!(event.getEntity() instanceof ServerPlayer victim)) return;
        if (!(event.getSource().getEntity() instanceof ServerPlayer killer)) return;
        if (killer == victim || killer instanceof FakePlayer || victim instanceof FakePlayer) return;
        AdvancementHolder holder = killer.server.getAdvancements().get(ADVANCEMENT_ID);
        if (holder == null) return;
        PlayerAdvancements advancements = killer.getAdvancements();
        if (advancements.getOrStartProgress(holder).isDone()) return;
        ItemStack head = makeHead(victim);
        if (!killer.addItem(head)) {
            killer.drop(head, false);
        }
        advancements.award(holder, CRITERION);
    }

    /** Eating the marked head applies the hidden infinite effect pair. */
    public static void onFinishUsing(LivingEntityUseItemEvent.Finish event) {
        if (!(event.getEntity() instanceof ServerPlayer player)) return;
        if (!isEdibleHead(event.getItem())) return;
        player.addEffect(infinite(MobEffects.REGENERATION));
        player.addEffect(infinite(MobEffects.WITHER));
    }

    /** Client-side: shows a vague "edible effects" block of colored scramble. */
    public static void onTooltip(ItemTooltipEvent event) {
        if (!isEdibleHead(event.getItemStack())) return;
        List<Component> tip = event.getToolTip();
        tip.add(Component.translatable(EFFECTS_KEY).withStyle(ChatFormatting.GRAY));
        for (int i = 0; i < SCRAMBLE_COLORS.length; i++) {
            tip.add(Component.translatable(SCRAMBLE_KEY + (i + 1))
                .withStyle(SCRAMBLE_COLORS[i])
                .withStyle(style -> style.withObfuscated(true)));
        }
    }

    private static ItemStack makeHead(ServerPlayer victim) {
        ItemStack stack = new ItemStack(Items.PLAYER_HEAD);
        // The live server GameProfile already carries the victim's skin data.
        stack.set(DataComponents.PROFILE, new ResolvableProfile(victim.getGameProfile()));
        stack.set(DataComponents.CUSTOM_NAME,
            Component.translatable(NAME_KEY, victim.getGameProfile().getName()));
        stack.set(DataComponents.FOOD,
            new FoodProperties(0, 0.0f, true, 1.6f, Optional.empty(), List.of()));
        CompoundTag tag = new CompoundTag();
        tag.putBoolean(TAG_MARKER, true);
        tag.putUUID(TAG_VICTIM_UUID, victim.getUUID());
        tag.putString(TAG_VICTIM_NAME, victim.getGameProfile().getName());
        stack.set(DataComponents.CUSTOM_DATA, CustomData.of(tag));
        return stack;
    }

    // INFINITE_DURATION is the real 1.21 infinite flag (same as `/effect ...
    // infinite`), so milk, death and /effect clear remove these normally.
    private static MobEffectInstance infinite(Holder<MobEffect> effect) {
        return new MobEffectInstance(
            effect, MobEffectInstance.INFINITE_DURATION, 5, false, false, false);
    }

    private static boolean isEdibleHead(ItemStack stack) {
        if (!stack.is(Items.PLAYER_HEAD)) return false;
        CustomData data = stack.get(DataComponents.CUSTOM_DATA);
        return data != null && data.copyTag().contains(TAG_MARKER);
    }
}
