// GENERATED by tools/build-pack.mjs — tooltip text comes from localization/*.
ItemEvents.tooltip((e) => {
  e.add('modpack:engineering_assembly', Text.translate('modpack.item.engineering_assembly.tooltip'))
  e.add('modpack:information_interface', Text.translate('modpack.item.information_interface.tooltip'))
  e.add('modpack:heavy_industry_control', Text.translate('modpack.item.heavy_industry_control.tooltip'))
  e.add('modpack:reactor_control', Text.translate('modpack.item.reactor_control.tooltip'))
  e.add('modpack:space_control_core', Text.translate('modpack.item.space_control_core.tooltip'))
  e.add('modpack:colony_maintenance', Text.translate('modpack.item.colony_maintenance.tooltip'))
  e.add('modpack:quantum_control', Text.translate('modpack.item.quantum_control.tooltip'))
  e.add('modpack:anomaly_analysis', Text.translate('modpack.item.anomaly_analysis.tooltip'))
  e.add('modpack:industrial_console', Text.translate('modpack.item.industrial_console.tooltip'))
  e.add('modpack:armory_workbench', Text.translate('modpack.item.armory_workbench.tooltip'))
  e.add('modpack:logistics_console', Text.translate('modpack.item.logistics_console.tooltip'))
  e.add('modpack:life_support_console', Text.translate('modpack.item.life_support_console.tooltip'))
});
