// GENERATED by tools/build-pack.mjs — tooltip text comes from localization/*.
ItemEvents.modifyTooltips((e) => {
  e.add('modpack:engineering_assembly', [Text.translate('item.modpack.engineering_assembly.tooltip')])
  e.add('modpack:information_interface', [Text.translate('item.modpack.information_interface.tooltip')])
  e.add('modpack:heavy_industry_control', [Text.translate('item.modpack.heavy_industry_control.tooltip')])
  e.add('modpack:reactor_control', [Text.translate('item.modpack.reactor_control.tooltip')])
  e.add('modpack:space_control_core', [Text.translate('item.modpack.space_control_core.tooltip')])
  e.add('modpack:colony_maintenance', [Text.translate('item.modpack.colony_maintenance.tooltip')])
  e.add('modpack:quantum_control', [Text.translate('item.modpack.quantum_control.tooltip')])
  e.add('modpack:anomaly_analysis', [Text.translate('item.modpack.anomaly_analysis.tooltip')])
  e.add('modpack:industrial_console', [Text.translate('item.modpack.industrial_console.tooltip')])
  e.add('modpack:armory_workbench', [Text.translate('item.modpack.armory_workbench.tooltip')])
  e.add('modpack:logistics_console', [Text.translate('item.modpack.logistics_console.tooltip')])
  e.add('modpack:life_support_console', [Text.translate('item.modpack.life_support_console.tooltip')])
  e.add('modpack:milestone_reward_pack', [Text.translate('item.modpack.milestone_reward_pack.tooltip')])
});
