// Audits Simplified Chinese localization coverage for the whole pack and
// writes docs/localization-report.md.
//
// Layers compared, per enabled mod jar and per lang namespace inside it:
//   assets/<ns>/lang/en_us.json            (source of truth, also config_defaults/)
//   assets/<ns>/lang/zh_cn.json            (bundled zh — preferred)
//   pack/kubejs/assets/<ns>/lang/zh_cn.json (our KubeJS overlay, generated by
//                                          gen-mod-lang-zh.mjs, may vendor CFPA)
//
// Beyond lang JSON it also checks: FTB Quests snbt lang parity, the generated
// progressivestages.toml message markers, starforge stage_i18n.json coverage,
// KubeJS scripts for hardcoded English, the compat mod's own lang pair, the
// EOS gunpack zip, and TaCZ custom pack langs under pack/kubejs.
//
// Statuses (Chinese, per docs requirement):
//   完整 / 少量缺失 / 部分汉化 / 严重缺失 / 未汉化 / 存在硬编码英文
//
// Run:  node tools/audit-lang.mjs          — write docs/localization-report.md
//       node tools/audit-lang.mjs --strict — also exit 1 when gaps remain

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const strict = process.argv.includes('--strict');

// ---------- jar helpers (same approach as gen-mod-lang-zh.mjs) ----------
function zipText(zip, entry) {
  try {
    return execFileSync('unzip', ['-p', zip, entry], { encoding: 'utf8', maxBuffer: 64 << 20 });
  } catch {
    return null;
  }
}
function zipList(zip) {
  let out;
  try {
    out = execFileSync('unzip', ['-Z1', zip], { encoding: 'utf8', maxBuffer: 64 << 20 });
  } catch {
    try {
      out = execFileSync('tar', ['-tf', zip], { encoding: 'utf8', maxBuffer: 64 << 20 });
    } catch {
      return [];
    }
  }
  return out.split('\n').map((s) => s.trim()).filter(Boolean);
}

// JSONC-tolerant parse: strips // and /* */ comments without touching "//"
// inside string literals (gunpack lang files are commented).
function parseJsonc(t) {
  if (t.charCodeAt(0) === 0xfeff) t = t.slice(1); // BOM — e.g. fastpipes zh_cn
  let o = '', s = false;
  for (let i = 0; i < t.length; i++) {
    const c = t[i];
    if (s) { o += c; if (c === '\\') o += t[++i] ?? ''; else if (c === '"') s = false; }
    else if (c === '"') { s = true; o += c; }
    else if (c === '/' && t[i + 1] === '/') { while (i < t.length && t[i] !== '\n') i++; o += '\n'; }
    else if (c === '/' && t[i + 1] === '*') { while (i < t.length && !(t[i] === '*' && t[i + 1] === '/')) i++; i++; }
    else o += c;
  }
  try { return JSON.parse(o); } catch { return null; }
}

const readJson = (f) => { try { return JSON.parse(readFileSync(f, 'utf8')); } catch { return null; } };

// ---------- heuristics ----------
// Values that are legitimately identical to English: ids, urls, placeholders,
// pure punctuation/digits, and short proper nouns (mod names). Everything else
// identical is reported as "zh identical to en" for manual review.
const looksTechnical = (v) =>
  /^[%§&@#^$<>{}\w:./\\+\-~|\s]*$/.test(v) && !/[a-z]{4,}\s+[a-z]{2,}/i.test(v) ||
  /^https?:\/\//.test(v) || /^[\w.]+:[\w./]+$/.test(v) || !/[^\x00-\x7F]/.test(v) && /^[A-Z0-9_\W]+$/.test(v);

const manifest = readJson(path.join(root, 'manifest/locked-mods.json'));
const enabledMods = manifest.mods.filter((m) => m.enabled && /\.jar$/i.test(m.filename));
const enabledRes = (manifest.resources ?? []).filter((r) => r.enabled);

const modsDir = path.join(root, 'mods');
const diskJars = new Set(readdirSync(modsDir).filter((f) => /\.jar$/i.test(f)));
const manifestFiles = new Set(enabledMods.map((m) => m.filename));
const extraJars = [...diskJars].filter((f) => !manifestFiles.has(f));
const missingJars = [...manifestFiles].filter((f) => !diskJars.has(f));

const kubejsAssets = path.join(root, 'pack/kubejs/assets');
const overlayZh = (ns) => {
  const f = path.join(kubejsAssets, ns, 'lang/zh_cn.json');
  return existsSync(f) ? readJson(f) ?? {} : {};
};

// ---------- 1. per-jar lang audit ----------
const LANG_RE = /^(?:config_defaults\/)?assets\/([^/]+)\/lang\/en_us\.json$/;
const rows = [];
const modsNoLang = [];

for (const mod of enabledMods) {
  const jar = path.join(modsDir, mod.filename);
  if (!existsSync(jar)) { missingJars.includes(mod.filename) || missingJars.push(mod.filename); continue; }
  const entries = zipList(jar);
  const langEn = entries.map((e) => e.match(LANG_RE)).filter(Boolean);
  if (!langEn.length) {
    modsNoLang.push({ key: mod.key, file: mod.filename, hasAssets: entries.some((e) => e.startsWith('assets/')) });
    continue;
  }
  for (const m of langEn) {
    const ns = m[1];
    const enPath = m[0];
    const zhPath = enPath.replace(/en_us\.json$/, 'zh_cn.json');
    const en = parseJsonc(zipText(jar, enPath) ?? '') ?? {};
    const zhRaw = zipText(jar, zhPath);
    const bundled = zhRaw === null ? null : parseJsonc(zhRaw) ?? {};
    const overlay = overlayZh(ns);
    const merged = { ...bundled, ...overlay }; // kubejs assets merge over jar lang
    const missing = [], empty = [], identical = [];
    for (const k of Object.keys(en)) {
      if (!(k in merged)) { missing.push(k); continue; }
      const v = merged[k];
      if (v === '' && en[k] !== '') empty.push(k);
      else if (v === en[k] && en[k] !== '' && !looksTechnical(en[k])) identical.push(k);
    }
    rows.push({
      mod: mod.key, file: mod.filename, ns, src: enPath.startsWith('config_defaults') ? 'config_defaults' : 'assets',
      en: Object.keys(en).length,
      bundled: bundled === null ? null : Object.keys(bundled).length,
      overlay: Object.keys(overlay).length,
      missing, empty, identical,
    });
  }
}

// ---------- 2. non-lang surfaces ----------
const extra = { issues: [], ok: [], notes: [] };

// 2a. FTB Quests snbt lang parity (en vs zh key sets)
{
  const dir = path.join(root, 'pack/config/ftbquests/quests/lang');
  const enT = existsSync(path.join(dir, 'en_us.snbt')) ? readFileSync(path.join(dir, 'en_us.snbt'), 'utf8') : '';
  const zhT = existsSync(path.join(dir, 'zh_cn.snbt')) ? readFileSync(path.join(dir, 'zh_cn.snbt'), 'utf8') : '';
  const keys = (t) => new Set([...t.matchAll(/^\s*([a-zA-Z0-9_.]+):/gm)].map((m) => m[1]));
  const enK = keys(enT), zhK = keys(zhT);
  const onlyEn = [...enK].filter((k) => !zhK.has(k));
  const onlyZh = [...zhK].filter((k) => !enK.has(k));
  if (onlyEn.length || onlyZh.length) {
    extra.issues.push(`FTB Quests snbt 语言文件键不一致：en-only ${onlyEn.length}，zh-only ${onlyZh.length}` +
      (onlyEn.length ? `（缺：${onlyEn.slice(0, 5).join(', ')}${onlyEn.length > 5 ? '…' : ''}）` : ''));
  } else {
    extra.ok.push(`FTB Quests snbt：en/zh 键完全一致（${enK.size} 键）`);
  }
  // chapter files should carry ids only — flag embedded English literals in
  // title/subtitle/description fields (text belongs in the lang files).
  const chapDir = path.join(root, 'pack/config/ftbquests/quests/chapters');
  if (existsSync(chapDir)) {
    const bad = [];
    for (const f of readdirSync(chapDir).filter((x) => x.endsWith('.snbt'))) {
      const t = readFileSync(path.join(chapDir, f), 'utf8');
      for (const m of t.matchAll(/(?:title|subtitle|description)\s*:\s*"([^"]*[a-zA-Z][^"]*)"/g)) {
        if (/[\u4e00-\u9fff]/.test(m[1])) continue;
        bad.push(`${f}: "${m[1].slice(0, 60)}"`);
      }
    }
    if (bad.length) extra.issues.push(`FTB Quests 章节内疑似英文硬编码：${bad.slice(0, 8).join('；')}`);
    else extra.ok.push('FTB Quests 章节文件：未发现英文硬编码文本（文本经 lang snbt 本地化）');
  }
}

// 2b. progressivestages.toml: every player-facing message must be a <ps:*> marker
//     or a bilingual "中文 / English" literal — plain English is the failure mode.
{
  const f = path.join(root, 'pack/config/progressivestages/progressivestages.toml');
  if (existsSync(f)) {
    const t = readFileSync(f, 'utf8');
    const msgs = [...t.matchAll(/^\s*(\w+)\s*=\s*"([^"]*)"/gm)];
    const plain = msgs.filter(([, k, v]) =>
      !v.includes('<ps:') && !/[\u4e00-\u9fff]\s*\/\s*/.test(v) &&
      /[a-zA-Z]{3,}\s+[a-zA-Z]/.test(v) && !/^(id|icon|sound|stage|group)$/.test(k));
    if (plain.length) {
      extra.issues.push(`progressivestages.toml 存在未经标记化的英文消息：${plain.map(([k]) => k).join(', ')}`);
    } else {
      extra.ok.push('progressivestages.toml：全部消息均为 <ps:*> 标记或双语字面量');
    }
  }
}

// 2c. stage_i18n.json covers every bilingual literal used in stage tomls
{
  const stagesDir = path.join(root, 'pack/config/progressivestages/stages');
  const i18n = readJson(path.join(root, 'pack/config/starforge/stage_i18n.json')) ?? {};
  const lits = new Set((i18n.pairs ?? []).map((p) => p.literal));
  if (existsSync(stagesDir)) {
    const uncovered = [];
    for (const d of readdirSync(stagesDir)) {
      const f = path.join(stagesDir, d, 'stage.toml');
      if (!existsSync(f)) continue;
      const t = readFileSync(f, 'utf8');
      for (const m of t.matchAll(/"([^"]*[\u4e00-\u9fff][^"]*\/[^"]*)"/g)) {
        if (!lits.has(m[1])) uncovered.push(`${d}: "${m[1].slice(0, 50)}"`);
      }
    }
    if (uncovered.length) extra.issues.push(`stage.toml 双语字面量未登记到 stage_i18n.json：${uncovered.slice(0, 8).join('；')}`);
    else extra.ok.push('stage_i18n.json：覆盖全部 stage.toml 双语字面量');
  }
}

// 2d. KubeJS scripts — hardcoded English in player-facing calls
{
  const scriptDirs = ['pack/kubejs/server_scripts', 'pack/kubejs/client_scripts', 'pack/kubejs/startup_scripts'];
  const hits = [];
  const re = /(?:tell|title|subtitle|actionbar|Text\.(?:of|red|green|gold|yellow|aqua|white|gray|dark_red|dark_green|dark_aqua|dark_blue|dark_purple|dark_gray|blue|black|light_purple))\s*\(?\s*['"`]([^'"`]*[a-zA-Z][^'"`]*)['"`]|"text"\s*:\s*"([^"]*[a-zA-Z][^"]*)"/g;
  for (const d of scriptDirs) {
    const dir = path.join(root, d);
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir).filter((x) => x.endsWith('.js'))) {
      const t = readFileSync(path.join(dir, f), 'utf8');
      for (const m of t.matchAll(re)) {
        const s = m[1] ?? m[2];
        if (/[\u4e00-\u9fff]/.test(s) || s.length < 8 || /translate|modpack\.|minecraft:|^[\w:./-]+$/.test(s)) continue;
        hits.push(`${path.basename(f)}: "${s.slice(0, 60)}"`);
      }
    }
  }
  if (hits.length) extra.issues.push(`KubeJS 脚本疑似硬编码英文：${[...new Set(hits)].slice(0, 8).join('；')}`);
  else extra.ok.push('KubeJS 脚本：未发现硬编码英文（经 Text.translate / translate 组件本地化）');
}

// 2e. compat mod lang parity
{
  const dir = path.join(root, 'compat/src/main/resources/assets/starforge_compat/lang');
  const en = readJson(path.join(dir, 'en_us.json')) ?? {};
  const zh = readJson(path.join(dir, 'zh_cn.json')) ?? {};
  const miss = Object.keys(en).filter((k) => !(k in zh));
  if (miss.length) extra.issues.push(`starforge_compat zh_cn 缺 ${miss.length} 键：${miss.slice(0, 5).join(', ')}`);
  else extra.ok.push(`starforge_compat：zh_cn 完整（${Object.keys(en).length} 键）`);
}

// 2f. TaCZ gun packs: EOS runtime zip + custom packs under pack/kubejs
{
  const checkPack = (label, enObj, zhObj, note) => {
    const miss = Object.keys(enObj).filter((k) => !(k in zhObj));
    if (miss.length) extra.issues.push(`${label} zh_cn 缺 ${miss.length} 键：${miss.slice(0, 5).join(', ')}`);
    else extra.ok.push(`${label}：zh_cn 完整（${Object.keys(enObj).length} 键${note ?? ''}）`);
  };
  const eosRes = enabledRes.find((r) => r.path?.includes('tacz/'));
  if (eosRes) {
    const z = path.join(root, 'run/client', eosRes.path);
    if (existsSync(z)) {
      const en = parseJsonc(zipText(z, 'assets/eos/lang/en_us.json') ?? '') ?? {};
      const zh = parseJsonc(zipText(z, 'assets/eos/lang/zh_cn.json') ?? '') ?? {};
      checkPack(`EOS 枪包（${eosRes.filename}）`, en, zh, '，JSONC');
    } else extra.notes.push(`EOS 枪包 ${eosRes.filename} 不在 run/client，跳过（发布时经 lockfile 提供）`);
  }
  const customRoot = path.join(kubejsAssets, 'tacz/custom');
  if (existsSync(customRoot)) {
    for (const pack of readdirSync(customRoot)) {
      const ld = path.join(customRoot, pack, 'assets/tacz/lang');
      if (!existsSync(ld)) continue;
      const en = readJson(path.join(ld, 'en_us.json')) ?? {};
      const zh = readJson(path.join(ld, 'zh_cn.json')) ?? {};
      const miss = Object.keys(en).filter((k) => !(k in zh));
      // covered-by-jar keys (tacz jar zh_cn merges over pack files)
      const jarZh = rows.find((r) => r.ns === 'tacz');
      const realMiss = jarZh ? miss.filter((k) => !(k in overlayZh('tacz'))) : miss;
      if (realMiss.length) extra.issues.push(`TaCZ 自定义包 ${pack} zh_cn 缺 ${realMiss.length} 键：${realMiss.slice(0, 5).join(', ')}`);
      else extra.ok.push(`TaCZ 自定义包 ${pack}：zh_cn 完整或经 tacz 命名空间覆盖（en ${Object.keys(en).length} 键）`);
    }
  }
}

// 2g. player-visible text in pack/config (excluding known-marker formats)
{
  const susFiles = [];
  const cfgDir = path.join(root, 'pack/config');
  const VAL_RE = /^\s*[\w.[\]-]+\s*=\s*"([^"]{12,})"/gm;
  const scan = (f) => {
    const t = readFileSync(f, 'utf8');
    const hits = [];
    for (const m of t.matchAll(VAL_RE)) {
      const v = m[1];
      if (/[\u4e00-\u9fff]/.test(v)) continue;
      if (!/^[A-Za-z][a-z]+( [A-Za-z][a-z]*){1,}[.!?]?$/.test(v)) continue;
      if (/^[\w.]+[:/]/.test(v) || v.includes('<ps:')) continue;
      hits.push(v.slice(0, 60));
    }
    return hits;
  };
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory() && !/^(progressivestages|ftbquests|starforge)/.test(e.name) && d === cfgDir) {
        // shallow scan of one level only — config tree is huge, focus on roots
        continue;
      }
      if (e.isDirectory()) { if (e.name !== 'toml_backups') walk(p); continue; }
      if (!/\.(toml|json|json5|snbt)$/i.test(e.name)) continue;
      const rel = path.relative(root, p).replace(/\\/g, '/');
      if (/ftbquests|progressivestages|starforge/.test(rel)) continue; // audited above
      const h = scan(p);
      if (h.length) susFiles.push(`${rel}（${h.length} 处，如 "${h[0]}"）`);
    }
  };
  if (existsSync(cfgDir)) walk(cfgDir);
  if (susFiles.length) extra.notes.push(`配置文件中疑似英文文本（人工复核）：${susFiles.slice(0, 10).join('；')}`);
  else extra.ok.push('pack/config：未发现疑似英文的玩家可见文本');
}

// ---------- 3. statuses ----------
const PCT = (r) => (r.en ? r.missing.length / r.en : 0);
function status(r) {
  if (r.en === 0) return '完整'; // empty en_us.json — nothing to translate
  if (r.bundled === null && r.overlay === 0) return '未汉化';
  const p = PCT(r);
  if (r.missing.length === 0 && r.empty.length === 0) return '完整';
  if (r.missing.length === 0) return '完整'; // empty values only — flagged in detail
  if (p <= 0.05 || r.missing.length <= 5) return '少量缺失';
  if (p <= 0.5) return '部分汉化';
  return '严重缺失';
}
for (const r of rows) r.status = status(r);

// Mods with no lang resources at all (hardcoded-English suspects)
const hardcoded = modsNoLang.map((m) => ({ ...m, status: '存在硬编码英文（无语言文件）' }));

// ---------- 4. report ----------
const statusOrder = ['完整', '少量缺失', '部分汉化', '严重缺失', '未汉化'];
const byStatus = {};
for (const r of rows) (byStatus[r.status] ??= []).push(r);

const lines = [];
const now = new Date().toISOString().slice(0, 10);
lines.push('# 简体中文本地化审计报告', '');
lines.push(`生成：\`node tools/audit-lang.mjs\` · ${now} · MC ${manifest.minecraft} / ${manifest.loader}`, '');
lines.push('覆盖层级：JAR 自带 `zh_cn`（优先）→ `pack/kubejs/assets/<ns>/lang/zh_cn.json` 覆盖层',
  '（`tools/gen-mod-lang-zh.mjs` 生成，含 vendor 的 CFPA/I18nUpdateMod 子集）。', '');

lines.push('## 汇总', '');
lines.push('| 指标 | 数量 |', '| --- | --- |');
lines.push(`| 启用 Mod（manifest） | ${enabledMods.length} |`);
lines.push(`| 有语言文件的 Mod / 命名空间 | ${new Set(rows.map((r) => r.mod)).size} / ${rows.length} |`);
lines.push(`| 无语言文件的 Mod | ${modsNoLang.length} |`);
lines.push(`| en_us 键总数 | ${rows.reduce((a, r) => a + r.en, 0)} |`);
lines.push(`| 缺失键总数 | ${rows.reduce((a, r) => a + r.missing.length, 0)} |`);
lines.push(`| zh 空值键 | ${rows.reduce((a, r) => a + r.empty.length, 0)} |`);
lines.push(`| zh 与 en 相同（可疑） | ${rows.reduce((a, r) => a + r.identical.length, 0)} |`);
lines.push('');
for (const s of statusOrder) {
  if (!byStatus[s]) continue;
  lines.push(`- **${s}**：${byStatus[s].length} 个命名空间`);
}
if (hardcoded.length) lines.push(`- **存在硬编码英文**：${hardcoded.length} 个 Mod`);
lines.push('');

if (extraJars.length || missingJars.length) {
  lines.push('## JAR 与 manifest 不一致', '');
  for (const f of extraJars) lines.push(`- mods/ 中存在但未锁定：\`${f}\``);
  for (const f of missingJars) lines.push(`- 已锁定但 mods/ 中缺失：\`${f}\``);
  lines.push('');
}

lines.push('## 各命名空间覆盖明细', '');
lines.push('| Mod | 命名空间 | 来源 | en 键 | 自带 zh | KubeJS 覆盖 | 缺失 | 空值 | 同英文 | 状态 |');
lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |');
for (const r of rows) {
  lines.push(`| ${r.mod} | ${r.ns} | ${r.src} | ${r.en} | ${r.bundled ?? '无'} | ${r.overlay || '-'} | ${r.missing.length || '-'} | ${r.empty.length || '-'} | ${r.identical.length || '-'} | ${r.status} |`);
}
lines.push('');

const listDetail = (title, pred) => {
  const sel = rows.filter(pred);
  if (!sel.length) return;
  lines.push(`### ${title}`, '');
  for (const r of sel) {
    lines.push(`- **${r.mod} / ${r.ns}**：缺 ${r.missing.length} 键`);
    for (const k of r.missing.slice(0, 12)) lines.push(`  - \`${k}\``);
    if (r.missing.length > 12) lines.push(`  - …另 ${r.missing.length - 12} 键`);
  }
  lines.push('');
};
listDetail('缺失明细（少量缺失）', (r) => r.status === '少量缺失');
listDetail('缺失明细（部分汉化）', (r) => r.status === '部分汉化');
listDetail('缺失明细（严重缺失）', (r) => r.status === '严重缺失');
listDetail('缺失明细（未汉化）', (r) => r.status === '未汉化');

const empties = rows.filter((r) => r.empty.length);
if (empties.length) {
  lines.push('### zh 空值（en 非空但 zh 为空串）', '');
  for (const r of empties) {
    lines.push(`- **${r.mod} / ${r.ns}**：${r.empty.map((k) => `\`${k}\``).join(', ')}`);
  }
  lines.push('');
}
const idents = rows.filter((r) => r.identical.length);
if (idents.length) {
  lines.push('### zh 与 en 完全相同（疑似未翻译；已排除 ID/占位符/纯大写）', '');
  for (const r of idents) {
    lines.push(`- **${r.mod} / ${r.ns}**：${r.identical.length} 键`);
    for (const k of r.identical.slice(0, 8)) lines.push(`  - \`${k}\``);
    if (r.identical.length > 8) lines.push(`  - …另 ${r.identical.length - 8} 键`);
  }
  lines.push('');
}

lines.push('## 语言文件之外的检查', '');
for (const s of extra.ok) lines.push(`- ✅ ${s}`);
for (const s of extra.notes) lines.push(`- ℹ️ ${s}`);
for (const s of extra.issues) lines.push(`- ❌ ${s}`);
lines.push('');

if (hardcoded.length) {
  lines.push('## 存在硬编码英文（无语言文件机制）', '');
  lines.push('以下 Mod 不含 `assets/<ns>/lang/`，其玩家可见文本由代码直接输出，',
    '语言文件无法覆盖，需 Mod 更新或 compat 层处理：', '');
  for (const m of hardcoded) lines.push(`- **${m.key}**（${m.file}）`);
  lines.push('');
  lines.push('已知字符串（ZombiesBreak&Build，经 `tools/dump-class-strings.ps1` 提取）：',
    '`Unknown config path:`、`Failed to save config`、`Failed to load config`、',
    '`Reloaded config`、`Invalid resource location`、`Not a collection config value` 等。',
    '这些仅在 `/zbb` 管理命令反馈中出现，普通玩家不可见。', '');
}

lines.push('## 状态判定标准', '');
lines.push('- **完整**：无缺失键');
lines.push('- **少量缺失**：缺失 ≤5 键 或 ≤5%');
lines.push('- **部分汉化**：缺失 ≤50%');
lines.push('- **严重缺失**：缺失 >50%');
lines.push('- **未汉化**：无自带 zh_cn 且无 KubeJS 覆盖');
lines.push('- **存在硬编码英文**：无语言文件机制，文本硬编码于代码中', '');

const outPath = path.join(root, 'docs/localization-report.md');
mkdirSync(path.dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n'));

// ---------- 5. console ----------
const totalMissing = rows.reduce((a, r) => a + r.missing.length, 0);
console.log(`audit-lang: ${rows.length} namespaces, ${totalMissing} missing keys, ` +
  `${modsNoLang.length} mods without lang, ${extra.issues.length} extra issues`);
console.log(`audit-lang: report -> ${path.relative(root, outPath)}`);
if (strict && (totalMissing || extra.issues.length)) process.exit(1);
