// Generates runtime pack files from design/ + localization/ sources.
// Sources: design/content.json, design/semantic-map.json, design/stage-locks.json,
//          localization/en_us.json, localization/zh_cn.json
// Outputs: pack/kubejs/**, pack/config/progressivestages/**
// Usage: node tools/build-pack.mjs
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { deflateSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const j = (p) => JSON.parse(readFileSync(path.join(root, p), 'utf8'));
const out = (p, data) => {
  const f = path.join(root, 'pack', p);
  mkdirSync(path.dirname(f), { recursive: true });
  writeFileSync(f, data);
};

const content = j('design/content.json');
const sm = j('design/semantic-map.json');
const locks = j('design/stage-locks.json');
const en = j('localization/en_us.json');
const zh = j('localization/zh_cn.json');
const NS = content.namespace; // modpack

// ---------- 1. KubeJS item registration ----------
const itemLines = content.items.map((i) => `  e.create('${NS}:${i.id}').texture('${NS}:item/${i.id}')`);
out('kubejs/startup_scripts/starforge_items.js',
`// GENERATED by tools/build-pack.mjs — edit design/content.json, not this file.
StartupEvents.registry('item', (e) => {
${itemLines.join('\n')}
});
`);

// ---------- 2. Semantic map (startup script — 'global' is writable there and shared) ----------
out('kubejs/startup_scripts/starforge_semantic_map.js',
`// GENERATED by tools/build-pack.mjs — edit design/semantic-map.json, not this file.
global.SM = ${JSON.stringify(sm, null, 1)};
`);

// ---------- 3. Lang files (item names/tooltips via keys) ----------
for (const [loc, dict] of [['en_us', en], ['zh_cn', zh]]) {
  const lang = {};
  for (const i of content.items) {
    lang[`item.${NS}.${i.id}`] = dict[i.name_key] ?? i.id;
    if (dict[i.tooltip_key]) lang[`item.${NS}.${i.id}.tooltip`] = dict[i.tooltip_key];
  }
  out(`kubejs/assets/${NS}/lang/${loc}.json`, JSON.stringify(lang, null, 1) + '\n');
}

// ---------- 4. Item models + generated placeholder textures ----------
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; t[n] = c; }
  return t;
})();
const crc32 = (buf) => { let c = 0xffffffff; for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; };
const pngChunk = (type, data) => {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type), data]);
  const crc = Buffer.alloc(4); crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
};
function makePng(hex) {
  const W = 16, H = 16;
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
  const dr = r >> 1, dg = g >> 1, db = b >> 1;
  const raw = Buffer.alloc(H * (1 + W * 4));
  for (let y = 0; y < H; y++) {
    raw[y * (1 + W * 4)] = 0;
    for (let x = 0; x < W; x++) {
      const o = y * (1 + W * 4) + 1 + x * 4;
      const border = x === 0 || y === 0 || x === W - 1 || y === H - 1;
      const diag = x === y;
      raw[o] = border ? dr : diag ? Math.min(255, r + 60) : r;
      raw[o + 1] = border ? dg : diag ? Math.min(255, g + 60) : g;
      raw[o + 2] = border ? db : diag ? Math.min(255, b + 60) : b;
      raw[o + 3] = 255;
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(W, 0); ihdr.writeUInt32BE(H, 4);
  ihdr[8] = 8; ihdr[9] = 6; // 8-bit RGBA
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk('IHDR', ihdr), pngChunk('IDAT', deflateSync(raw)), pngChunk('IEND', Buffer.alloc(0))
  ]);
}
const itemColors = {
  engineering_assembly: 'b08040', information_interface: '40b0c0', heavy_industry_control: '804040',
  reactor_control: '40a040', space_control_core: '4060d0', colony_maintenance: 'd0a030',
  quantum_control: 'a040c0', anomaly_analysis: '30c0a0',
  industrial_console: '606060', armory_workbench: '804030', logistics_console: '306090', life_support_console: '309060'
};
for (const i of content.items) {
  out(`kubejs/assets/${NS}/models/item/${i.id}.json`,
    JSON.stringify({ parent: 'item/generated', textures: { layer0: `${NS}:item/${i.id}` } }, null, 1) + '\n');
  out(`kubejs/assets/${NS}/textures/item/${i.id}.png`, makePng(itemColors[i.id] ?? '808080'));
}

// ---------- 4b. Client tooltips (translatable keys) ----------
const tipEntries = content.items
  .map((i) => `  e.add('${NS}:${i.id}', [Text.translate('${i.tooltip_key}')])`)
  .join('\n');
out('kubejs/client_scripts/starforge_tooltips.js',
`// GENERATED by tools/build-pack.mjs — tooltip text comes from localization/*.
ItemEvents.modifyTooltips((e) => {
${tipEntries}
});
`);

// ---------- 5. ProgressiveStages global config ----------
// Keep the mod's defaults but grant T0 on first join.
out('config/progressivestages/progressivestages.toml',
`# GENERATED by tools/build-pack.mjs — Starforge ProgressiveStages global config.
[general]
	starting_stages = ["${NS}:survival_age"]
	team_mode = "ftb_teams"
	debug_logging = false
	linear_progression = false
	reapply_starting_stages_on_login = true
`);

// ---------- 6. Stage definitions ----------
const stageIcons = {
  survival_age: 'minecraft:crafting_table',
  mechanical_age: `${NS}:engineering_assembly`,
  electric_age: 'ic2cre:generator',
  information_age: `${NS}:information_interface`,
  heavy_industry_age: `${NS}:heavy_industry_control`,
  atomic_age: `${NS}:reactor_control`,
  space_age: `${NS}:space_control_core`,
  quantum_age: `${NS}:quantum_control`
};
const stageColors = {
  survival_age: '#8b8b8b', mechanical_age: '#c07f3f', electric_age: '#e0b030',
  information_age: '#3fa8c8', heavy_industry_age: '#a05050', atomic_age: '#4fae5f',
  space_age: '#4f6fd8', quantum_age: '#a05fd0'
};
const stageRoot = `config/progressivestages/stages`;
const stageDir = path.join(root, 'pack', stageRoot);
if (existsSync(stageDir)) rmSync(stageDir, { recursive: true, force: true });

const tomlStr = (s) => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const tomlList = (arr) => `[${arr.map(tomlStr).join(', ')}]`;

for (const st of content.stages) {
  const deps = st.depends_on.map((d) => `${NS}:${d}`);
  const zhName = zh[st.name_key] ?? st.id;
  const enName = en[st.name_key] ?? st.id;
  const zhDesc = zh[st.description_key] ?? '';
  const enDesc = en[st.description_key] ?? '';
  const dir = `${stageRoot}/${st.id}`;
  out(`${dir}/stage.toml`,
`[schema]
version = 4

[stage]
id = "${NS}:${st.id}"
display_name = ${tomlStr(`${zhName} / ${enName}`)}
description = ${tomlStr(`${zhDesc} / ${enDesc}`)}
icon = "${stageIcons[st.id] ?? 'minecraft:stone'}"
dependencies = ${tomlList(deps)}
dependency_mode = "all"
category = "Starforge"
color = "${stageColors[st.id] ?? '#888888'}"
hidden = false
scope = "team"
tags = ["modpack", "tier_${st.tier}"]

[display]
frame = ${st.tier >= 6 ? '"challenge"' : '"task"'}
reveal = "dependencies"
`);

  // progression.toml — trigger rules granting this stage from unlock_evidence.
  // PS schema-4 format: [[triggers]] rules each with a conditions list.
  // mode=any_of so EITHER the native craft stat OR the KubeJS-driven
  // custom_counter (starforge_triggers.js on ItemEvents.crafted) grants it.
  const ev = st.unlock_evidence;
  let prog = '';
  if (ev && ev.type === 'server_verified_production' && ev.component) {
    const itemId = sm.items[ev.component];
    if (!itemId) throw new Error(`stage ${st.id}: unlock_evidence component ${ev.component} not in semantic map`);
    prog = `[[triggers]]
mode = "any_of"
description = "Craft the stage evidence item"
[[triggers.conditions]]
type = "craft"
item = "${itemId}"
count = 1
[[triggers.conditions]]
type = "custom_counter"
counter = "${NS}:craft_${ev.component}"
count = 1
`;
  }
  out(`${dir}/progression.toml`, prog);

  // rules.toml — item use-lock, block place-lock, recipe output lock, dimension enter-lock
  const lock = locks[st.id] ?? { items: [], blocks: [], dimensions: [] };
  const itemIds = (lock.items ?? []).map((k) => {
    const id = sm.items[k];
    if (!id) throw new Error(`stage ${st.id}: unmapped lock item ${k}`);
    return id;
  });
  const dimIds = (lock.dimensions ?? []).map((k) => {
    const id = sm.dimensions[k];
    if (!id) throw new Error(`stage ${st.id}: unmapped lock dimension ${k}`);
    return id;
  });
  let rules = '';
  if (itemIds.length) {
    rules += `[[rules]]
id = "${NS}:${st.id}/lock_use"
effect = "lock"
action = "use"
priority = 500
targets.items = ${tomlList(itemIds)}

[[rules]]
id = "${NS}:${st.id}/lock_place"
effect = "lock"
action = "place"
priority = 500
targets.blocks = ${tomlList(itemIds)}

[recipes]
locked_items = ${tomlList(itemIds)}
`;
  }
  if (dimIds.length) {
    rules += `
[[rules]]
id = "${NS}:${st.id}/lock_dim_enter"
effect = "lock"
action = "enter"
priority = 500
targets.dimensions = ${tomlList(dimIds)}
`;
  }
  out(`${dir}/rules.toml`, rules);
}

console.log(`build-pack: generated ${content.items.length} items, ${content.stages.length} stages, 2 lang files`);
