[[rules]]
id = "modpack:quantum_age/lock_use"
effect = "lock"
action = "use"
priority = 500
targets.items = ["ic2cre:quantum_helmet", "ic2cre:quantum_chestplate", "ic2cre:quantum_leggings", "ic2cre:quantum_boots", "ae2:quantum_ring", "ae2:quantum_link", "ae2:spatial_storage_cell_128"]

[[rules]]
id = "modpack:quantum_age/lock_place"
effect = "lock"
action = "place"
priority = 500
targets.blocks = ["ic2cre:quantum_helmet", "ic2cre:quantum_chestplate", "ic2cre:quantum_leggings", "ic2cre:quantum_boots", "ae2:quantum_ring", "ae2:quantum_link", "ae2:spatial_storage_cell_128"]

[recipes]
locked_items = ["ic2cre:quantum_helmet", "ic2cre:quantum_chestplate", "ic2cre:quantum_leggings", "ic2cre:quantum_boots", "ae2:quantum_ring", "ae2:quantum_link", "ae2:spatial_storage_cell_128"]
